# Generated by Django 4.1.1 on 2022-10-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customuser_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(default="images/default.bng", upload_to="images/"),
        ),
    ]
