# Generated by Django 4.1.1 on 2022-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_customuser_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(default="/images/default.png", upload_to="images/"),
        ),
    ]
