# Generated by Django 4.1.1 on 2022-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forbiddenword",
            name="instead",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
