# Generated by Django 4.1.1 on 2022-10-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_comment_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts_tags",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_tags",
                to="post.tag",
            ),
        ),
    ]
