# Generated by Django 4.1.1 on 2022-10-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_alter_posts_tags_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts_tags",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_tags",
                to="post.post",
            ),
        ),
    ]
